In [15]:
import pandas as pd
import numpy as np
import hashlib


print("Pandas: ", pd.__version__)
print("Numpy: ", np.__version__)

# hashing
hashing = lambda x : hashlib.sha256(x.encode()).hexdigest()


# import the cleaning data
pd.set_option("display.max_columns", 25)
df_cleaned = pd.read_csv("../data/processed/data_cleaned.csv")

df_cleaned.columns.tolist()

Pandas:  3.0.5
Numpy:  1.26.4

['Unnamed: 0',
 'Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Days',
 'Estimated Days',
 'Price',
 'Product Cost']

In [16]:

personal_columns = [
    'Customer Name',
    'Customer ID',
]

for col in personal_columns:
    if col in df_cleaned.columns:
        print(f"\n--- {col} ---")
        print(df_cleaned[col].head())
        print("Unique:", df_cleaned[col].nunique())
        print("Missing:", df_cleaned[col].isna().sum())

--- Customer Name ---
0        claire gute
1        claire gute
2    darrin huff van
3     o'donnell sean
4     o'donnell sean
Name: Customer Name, dtype: str
Unique: 793
Missing: 0

--- Customer ID ---
0    CG-12520
1    CG-12520
2    DV-13045
3    SO-20335
4    SO-20335
Name: Customer ID, dtype: str
Unique: 793
Missing: 0

In [17]:
# pseudonymize the Customer ID

df_cleaned['Customer ID Pseudo'] = df_cleaned['Customer ID'].astype(str).apply(hashing)

display(df_cleaned[['Customer ID', 'Customer ID Pseudo']].head())
# drop the Customer ID
df_cleaned = df_cleaned.drop(columns=['Customer ID'])

  Customer ID                                 Customer ID Pseudo
0    CG-12520  860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
1    CG-12520  860dcbde13f3d5792bd7ed41a7b6890ca3a75b65508bbc...
2    DV-13045  3e049414e32502b60fdeca0439b42f7560263e8e88a224...
3    SO-20335  e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...
4    SO-20335  e82c08dc9dbace252fe1d9bc3e97034dc878e66f8ed297...

In [18]:
# pseudonymize the Customer Name

df_cleaned['Customer Name Pseudo'] = df_cleaned['Customer Name'].astype(str).apply(hashing)

display(df_cleaned[['Customer Name', 'Customer Name Pseudo']].head())
# drop the Customer Name
df_cleaned = df_cleaned.drop(columns=['Customer Name'])

     Customer Name                               Customer Name Pseudo
0      claire gute  9173dadf359b0cb7e29c9a654dab0904da9084fb419dbb...
1      claire gute  9173dadf359b0cb7e29c9a654dab0904da9084fb419dbb...
2  darrin huff van  5b4e754f05b1fa69137b2b54a28294cedb8447600d5ccb...
3   o'donnell sean  f5d6f90f48af7497ffe2d1368cea8edd968e7625433453...
4   o'donnell sean  f5d6f90f48af7497ffe2d1368cea8edd968e7625433453...